feat(issue-41): set and inherit labels
kiegroup/git-backporting pull request #48
Opened 2023-07-07 10:37 UTC by lampajr

fix https://github.com/kiegroup/git-backporting/issues/41

**Thank you for submitting this pull request**

fix _(please add the issue ID if it exists)_

### Referenced pull requests

### Checklist
- [ ] Tests added if applicable.
- [ ] Documentation updated if applicable.

> **Note:** `dist/cli/index.js` and `dist/gha/index.js` are automatically generated by git hooks and gh workflows.

2023-07-07 14:42 UTC, lampajr commented
In addition to the enhancement itself, I improved a bit the test coverage, here the results right now:
```
----------------------------|---------|----------|---------|---------|-------------------------------
File                        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s             
----------------------------|---------|----------|---------|---------|-------------------------------
All files                   |   90.25 |       80 |   89.28 |   90.39 |                               
 args                       |   95.83 |     92.3 |     100 |   95.65 |                               
  args-parser.ts            |   83.33 |       80 |     100 |   83.33 | 21                            
  args-utils.ts             |     100 |      100 |     100 |     100 |                               
 args/cli                   |     100 |      100 |     100 |     100 |                               
  cli-args-parser.ts        |     100 |      100 |     100 |     100 |                               
 args/gha                   |     100 |      100 |     100 |     100 |                               
  gha-args-parser.ts        |     100 |      100 |     100 |     100 |                               
 configs                    |     100 |      100 |     100 |     100 |                               
  configs-parser.ts         |     100 |      100 |     100 |     100 |                               
 configs/pullrequest        |    91.3 |    96.29 |     100 |    91.3 |                               
  pr-configs-parser.ts      |    91.3 |    96.29 |     100 |    91.3 | 22-23                         
 git                        |    82.5 |    53.57 |   76.47 |   82.05 |                               
  git-cli.ts                |    62.5 |    21.42 |      60 |    62.5 | 38-43,63-67,88-89,109-110,124 
  git-client-factory.ts     |    90.9 |       60 |     100 |    90.9 | 18,46                         
  git-util.ts               |     100 |      100 |     100 |     100 |                               
  git.types.ts              |     100 |      100 |     100 |     100 |                               
 git/github                 |   91.07 |    84.61 |   88.23 |   92.59 |                               
  github-client.ts          |   91.42 |       75 |     100 |   91.42 | 66,91,104                     
  github-mapper.ts          |   84.61 |     87.5 |   77.77 |    90.9 | 28                            
  octokit-factory.ts        |     100 |      100 |     100 |     100 |                               
 git/gitlab                 |   95.18 |    65.21 |     100 |   95.18 |                               
  gitlab-client.ts          |   96.82 |       75 |     100 |   96.82 | 147,151                       
  gitlab-mapper.ts          |      90 |       60 |     100 |      90 | 23,78                         
 logger                     |   88.88 |      100 |   77.77 |   88.88 |                               
  console-logger-service.ts |      90 |      100 |   83.33 |      90 | 15                            
  logger-service-factory.ts |     100 |      100 |     100 |     100 |                               
  logger.ts                 |   66.66 |      100 |      50 |   66.66 | 13                            
 runner                     |   84.78 |      100 |   66.66 |   84.78 |                               
  runner.ts                 |   84.78 |      100 |   66.66 |   84.78 | 30-40                         
----------------------------|---------|----------|---------|---------|-------------------------------
Test Suites: 14 passed, 14 total
Tests:       103 passed, 103 total
Snapshots:   0 total
```

2023-07-07 16:21 UTC, shubhbapna requested changes

2023-07-07 17:05 UTC, lampajr commented on src/service/args/args-utils.ts
> +export function getAsCleanedCommaSeparatedList(value: any): string[] | undefined {
leftover, thx for spotting this

2023-07-07 17:08 UTC, lampajr commented on src/service/git/github/github-client.ts
> +
I definitely agree with you, I was not thinking about that.
I would open an issue for this and do that in a separate PR if you agree.

2023-07-07 17:22 UTC, shubhbapna commented on src/service/git/github/github-client.ts
> +
Yep sounds good!

2023-07-07 17:23 UTC, shubhbapna commented
Also for the code coverage we can enable sonar cloud for the project so that for each PR we can view the coverage info on sonar cloud automatically. Wdyt?

2023-07-07 17:26 UTC, shubhbapna commented on src/service/git/github/github-client.ts
> +
issue created: https://github.com/kiegroup/git-backporting/issues/49

2023-07-07 17:26 UTC, shubhbapna approved these changes

2023-07-09 19:34 UTC, lampajr commented on src/service/git/github/github-client.ts
> +
thanks!

2023-07-09 19:52 UTC, lampajr commented
> Also for the code coverage we can enable sonar cloud for the project so that for each PR we can view the coverage info on sonar cloud automatically. Wdyt?

Yeah that is for sure a great improvement, created https://github.com/kiegroup/git-backporting/issues/50 to keep track of this :)

2023-07-10 06:26 UTC, Ginxo approved these changes
LGTM, just package.json version should be upgraded right? also CHANGELOG...
many thanks for this :heart:

2023-07-10 06:34 UTC, lampajr commented
> LGTM, just package.json version should be upgraded right? also CHANGELOG... many thanks for this heart

I created this workflow [1] to automatically update (based on diff commits) both package.json and CHANGELOG such that we do not have to do it manually. I already added **release** section [2] in the README. 

[1] https://github.com/kiegroup/git-backporting/actions/workflows/prepare-release.yml
[2] https://github.com/kiegroup/git-backporting/#release

2023-07-10 06:49 UTC, merged